#!/bin/bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

#find -name \*.o -o -name \*.a | xargs rm

set -e

cd "$(dirname "$0")/.."

if [ "$FUZZER" = 1 ]; then
    export EMULATOR=1
    export HEADLESS=1
    export CC=clang-7
    export CFLAGS="-fsanitize=fuzzer,address,undefined"
    export LDFLAGS="-fsanitize=fuzzer,address,undefined"
    make -C fuzzer
elif [ "$EMULATOR" = 1 ]; then
    make -C emulator
else
    make -C vendor/libopencm3 lib/stm32/f2
fi

make
if [ "$EMULATOR" != 1 ]; then
    make -C bootloader
fi
make -C vendor/nanopb/generator/proto
make -C firmware/protob

make -C firmware
